-- Drop tables if they exist to avoid duplication
DROP TABLE IF EXISTS VIC_CYBERBULLYING_PERCENT CASCADE;
DROP TABLE IF EXISTS VIC_MENTAL_HEALTH CASCADE;
DROP TABLE IF EXISTS CYBERBULLYING_DATASET CASCADE;
DROP TABLE IF EXISTS EMOJI_MEANINGS CASCADE;

-- Table: VIC_CYBERBULLYING_PERCENT
CREATE TABLE VIC_CYBERBULLYING_PERCENT (
    year INT NOT NULL,
    age_group VARCHAR(50) NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (year)
);

-- Table: VIC_MENTAL_HEALTH
CREATE TABLE VIC_MENTAL_HEALTH (
    year INT NOT NULL,
    age_group VARCHAR(50) NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (year)
);

-- Table: CYBERBULLYING_DATASET
CREATE TABLE CYBERBULLYING_DATASET (
    sr_no SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    label VARCHAR(100) NOT NULL
);

-- Table: EMOJI_MEANINGS
CREATE TABLE EMOJI_MEANINGS (
    id SERIAL PRIMARY KEY,
    emoji TEXT,
    actual_meaning TEXT,
    hidden_meaning TEXT,
    category TEXT,
    example TEXT
);

